namespace: project-controller
configMapGenerator:
  - name: project-controller-envs
    literals:
      - TZ=Asia/Seoul
      - SERVER_SSL_KEY_STORE=/etc/project-controller/tls/tls.p12
      - APP_AIPUB_ENABLED=false
      - APP_AIPUB_SERVER_URL=https://aipub.clutser6.idc1.ten1010.io
      - APP_AIPUB_VERIFYING-SSL=false
      - APP_AIPUB_USERNAME=testuser
      - APP_AIPUB_PASSWORD=asdasdasd
      - APP_AIPUB_RESERVED_NAMESPACE=aipub,k10s,project-controller,coaster
secretGenerator:
  - name: project-controller-envs
    literals:
      - SERVER_SSL_KEY_STORE_PASSWORD=""
  - name: project-controller-tls
    files:
      - tls.p12
generatorOptions:
  disableNameSuffixHash: true
resources:
  - templates/namespace.yaml
  - templates/service-account.yaml
  - templates/cluster-role.yaml
  - templates/role.yaml
  - templates/crd.yaml
  - templates/deployment.yaml
  - templates/service.yaml
  - templates/mutating-webhook-configuration.yaml
patchesStrategicMerge:
  - patches.yaml
