spring:
  application:
    name: project-controller
  profiles:
    active: "production"
  web:
    resources:
      add-mappings: false
  http:
    converters:
      preferred-json-mapper: jackson2
  jackson:
    use-jackson2-defaults: true


server:
  forward-headers-strategy: framework

app:
  k8s:
    verify-ssl: false
    kube-config:
      mode: in_cluster
      # kube-config-path: /users/user/.kube/config
  aipub:
    enabled: false
    server-url: "https://aipub.example.com"
    harbor-external-url: "https://aipub-harbor.example.com"
    verifying-ssl: false
    username: "testuser"
    password: "asdasdasd"
    reserved-namespace: "aipub, project-controller"
    add-owner-except-gvk-list:
      - "aipub.ten1010.io/v1alpha1/Commit"
      - "aipub.ten1010.io/v1/Commit"
      - "aipub.ten1010.io/v1alpha1/UserAuthorityReview"
      - "aipub.ten1010.io/v1/UserAuthorityReview"
    reconcile-excluded-label-selectors:
      - "app.kubernetes.io/part-of=cilium"
      - "kubevirt.io"
