namespace: project-controller

configMapGenerator:
  - name: project-controller-envs
    literals:
      - TZ=Asia/Seoul
      - SERVER_SSL_KEY_STORE=/etc/project-controller/tls/tls.p12
      - APP_AIPUB_ENABLED=false
      - APP_AIPUB_SERVER_URL=http://localhost:8080
      - APP_AIPUB_VERIFYING-SSL=false
      - APP_AIPUB_USERNAME=testuser
      - APP_AIPUB_PASSWORD=testpass
      - APP_AIPUB_RESERVED_NAMESPACE=project-controller

secretGenerator:
  - name: project-controller-envs
    literals:
      - SERVER_SSL_KEY_STORE_PASSWORD=""
  - name: project-controller-tls
    files:
      - tls.p12

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../kubernetes/controller/project-controller/templates/namespace.yaml
  - ../kubernetes/controller/project-controller/templates/service-account.yaml
  - ../kubernetes/controller/project-controller/templates/cluster-role.yaml
  - ../kubernetes/controller/project-controller/templates/role.yaml
  - ../kubernetes/controller/project-controller/templates/crd.yaml
  - ../kubernetes/controller/project-controller/templates/deployment.yaml
  - ../kubernetes/controller/project-controller/templates/service.yaml
  - ../kubernetes/controller/project-controller/templates/mutating-webhook-configuration.yaml

patchesStrategicMerge:
  - patches.yaml
