apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tcpportvalidators.aipub.ten1010.io
spec:
  conversion:
    strategy: None
  group: aipub.ten1010.io
  names:
    kind: TCPPortValidator
    listKind: TCPPortValidatorList
    plural: tcpportvalidators
    shortNames:
      - tpv
    singular: tcpportvalidator
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                port:
                  type: integer
              required:
                - port
              type: object
            status:
              properties:
                available:
                  type: boolean
              type: object
          type: object
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gpuconfigs.coaster.ten1010.io
spec:
  conversion:
    strategy: None
  group: coaster.ten1010.io
  names:
    categories:
      - all
    kind: GPUConfig
    listKind: GPUConfigList
    plural: gpuconfigs
    shortNames:
      - gpuconf
      - gconfig
      - gconf
    singular: gpuconfig
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .metadata.name
          name: NODE_NAME
          type: string
        - jsonPath: .status.completionCondition.status
          name: COMPLETED
          type: boolean
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            metadata:
              type: object
            spec:
              properties:
                gpus:
                  default: []
                  items:
                    properties:
                      gpuIndex:
                        type: integer
                        x-kubernetes-validations:
                          - message: gpuIndex must be zero or greater
                            rule: self >= 0
                      migCount:
                        type: integer
                        x-kubernetes-validations:
                          - message: migCount must be between 2 and 7
                            rule: self >= 2 && self <= 7
                      type:
                        type: string
                        x-kubernetes-validations:
                          - message: Invalid type. type must be one of 'Normal' and 'Block'
                            rule: self in ["Normal", "Block"]
                    required:
                      - gpuIndex
                      - type
                    type: object
                    x-kubernetes-validations:
                      - message: migCount can only be used when type is Normal
                        rule: '!((self.type == ''Block'') && has(self.migCount))'
                  maxItems: 32
                  type: array
                  x-kubernetes-validations:
                    - message: gpuIndex must be unique
                      rule: self.all(x, size(self.filter(y, y.gpuIndex == x.gpuIndex))
                        == 1)
              required:
                - gpus
              type: object
            status:
              default:
                gpus: []
              properties:
                completionCondition:
                  properties:
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: boolean
                    timestamp:
                      type: string
                  type: object
                gpus:
                  items:
                    properties:
                      gpuIndex:
                        type: integer
                      migCount:
                        type: integer
                      type:
                        type: string
                    type: object
                  maxItems: 32
                  type: array
              type: object
          required:
            - metadata
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcesets.aipub.ten1010.io
spec:
  conversion:
    strategy: None
  group: aipub.ten1010.io
  names:
    categories:
      - all
    kind: ResourceSet
    listKind: ResourceSetList
    plural: resourcesets
    shortNames:
      - rss
    singular: resourceset
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.cpu
          name: CPU
          type: string
        - jsonPath: .spec.memory
          name: MEMORY
          type: string
        - jsonPath: .spec.gpu
          name: GPU
          type: string
        - jsonPath: .status.category
          name: CATEGORY
          type: string
        - jsonPath: .status.ready
          name: READY
          type: boolean
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            metadata:
              type: object
            spec:
              properties:
                cpu:
                  type: string
                gpu:
                  type: string
                memory:
                  type: string
                nodes:
                  items:
                    properties:
                      nodeName:
                        type: string
                      resourcesetCount:
                        type: integer
                    type: object
                  type: array
              required:
                - cpu
                - memory
              type: object
            status:
              properties:
                category:
                  type: string
                nodes:
                  items:
                    properties:
                      nodeName:
                        type: string
                      resourcesetCount:
                        type: integer
                    type: object
                  type: array
                ready:
                  type: boolean
                resourceName:
                  type: string
              type: object
          required:
            - metadata
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
---
