apiVersion: project.aipub.ten1010.io/v1alpha1
kind: NodeMaintenance
metadata:
  name: node1-maintenance
spec:
  targetNodes:
    - minikube-m02
#    - minikube-m03
  actions:
#    - type: uncordon
    - type: drain
      ignoreDaemonSets: false
      force: true
