apiVersion: project.aipub.ten1010.io/v1alpha1
kind: Project
metadata:
  name: proj1
spec:
  members:
    - aipubUser: au1
      role: project-manager
    - aipubUser: au2
      role: project-developer
  quota:
    hard:
      requests.cpu: "16"
      limits.cpu: "32"
      requests.memory: 64Gi
      limits.memory: 128Gi
      requests.storage: 500Gi
      requests.ten1010.io/gpu-block-63mb-a2000: "8"
  binding:
    nodes:
      - node1
    nodeGroups:
      - ng1
    imageHubs:
      - img-hub1
---
