apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-controller.fullname" . }}-envs
  namespace: {{ include "project-controller.namespace" . }}
  labels:
    {{- include "project-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  SERVER_SSL_KEY_STORE_PASSWORD: {{ .Values.secrets.sslKeyStorePassword | quote }}
---
{{- if .Values.tls.p12 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-controller.fullname" . }}-tls
  namespace: {{ include "project-controller.namespace" . }}
  labels:
    {{- include "project-controller.labels" . | nindent 4 }}
type: Opaque
data:
  tls.p12: {{ .Values.tls.p12 }}
{{- end }}
