apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "project-controller.fullname" . }}
  namespace: {{ include "project-controller.namespace" . }}
  labels:
    {{- include "project-controller.labels" . | nindent 4 }}
